#python programing questions No.12
#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle numer would be
# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28
#The first ten terms would be:
# 1 ,3, 6, 10, 15, 21, 28, 36, 45, 55 ....
#let us list the factors of the first seven triangle numbers:
#1: 1
#3: 1, 3
#6: 1, 2, 3, 6
#10: 1, 2, 5, 10
#15: 1, 3, 5, 15
#21: 1, 3, 7, 21
#28: 1, 2, 4, 7, 14, 28
#we can see that 28 is the first triangle number to have over five divisors.
#what is the value of the first triangle number to have over !five hundred! divisors?

#version 0.1

def makeTrian():
    number =4
    trian =0
    divider =1
    temp0 =0
    listOfD =[]
    sum0 =0

    for i in range(0,5):
        trian = number*(number+ 1)/2

        while True:
            temp0 =trian %divider #test if trian can be divided in to int
            print (temp0)

            if temp0 ==0:
                listOfD.append(divider)
                print('append')
            if temp0 !=0:
                print('do nothing to list, increase divider')

            divider =divider +1 #increase divider
            print(listOfD)


            if divider == trian and len(listOfD) < 5:
                listOfD.append(divider)
                print('Trian need increase--')
                break

            if len(listOfD)==5:
                sys.exit('x')






                '''if len(listOfD) ==5:
                    print('Done!')
                    for i in range(0, len(listOfD)):
                        sum0 =listOfD[i]+sum0
                        print(sum0)
                    print('finished')
                    print(listOfD)
                    print("number" +str(number))
                    sys.exit("done")

                '''


        print('test')
        listOfD =[]
        number =number +1

'''----------------------------------------------------------'''



print (makeTrian())


