#python programing questions No.2
#even fibonacci numbers
#Each new term in fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms is:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89....
#by considering the terms in the fibonacci sequence whos values do not exceed 4 mil, find the sum of the even-valued terms

#version 0.1
ints =[1,2]
intsIndex1 =0
intsIndex2 =1
fib0 =0
sum0 =0

while True:
    fib0  =ints[intsIndex1] +ints[intsIndex2]
    ints.append(fib0)
    intsIndex1 =intsIndex1+1
    intsIndex2 =intsIndex2+1
    if fib0 > 4000000:
        break
    
for a in range(0,len(ints)): #a will only be use here
    result = ints[a]%2
    if result >0:
        ints[a] =0
    sum0 =ints[a] +sum0
    

str0 ='The list will looks like: '
str1 ='The sum of all even fib numbers: '
    
print(str0+ str(ints))
print(str1+ str(sum0))

'''----------------------------------------------------------------------------------------------'''